name: Build

env:
  MAVEN_ARGS: -V -ntp -e

on:
  workflow_call:
    inputs:
      kube-version:
        type: string
        required: true

jobs:
  test_with_kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.13.1
        with:
          minikube version: 'v1.34.0'
          kubernetes version: '${{ inputs.kube-version }}'
          driver: 'docker'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Integration tests
        uses: ./.github/workflows/build.yml
